### ISSUE TITLE
version `OPENSSL_1.0.0' not found

### ISSUE THREAD

**Issue by arnauhe** [google/cups-connector#114]
Hi,
Trying to run gcp-cups-connector but error appears : 
./gcp-cups-connector: /usr/lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./gcp-cups-connector)
..cause I've installed latest version of openssl earlier then now I'm facing issues to uninstall openssl-1.0.1 version.
rpm -e openssl-1.0.0-10.el6.x86_64� doesn't works and errors occured tied to dependencies :
error: Failed dependencies:
        libcrypto.so.10()(64bit) is needed by (installed) wget-1.12-5.el6_6.1.x86_64�...

Yet openssl version command return:
OpenSSL 1.0.0s 11 Jun 2015

Thank you
------------------------
Red Hat Enterprise Linux Server release 6.7 (Santiago)�
CUPS :  gcp-cups-connector-linux-amd64-2015.10.05

**Comment by jacobmarble** [comment]
@arnauhe you closed this issue, so I take it you solved the problem? Building yourself should fix the problem; let me know if I can help.

**Comment by arnauhe** [comment]
Hi,
Yes, actually, I still encountered issues with openssl version. GCP cups connector required 1.0.1 but when I tried to downgrade this package, errors occured with ssh libraries and others..
Is there no way to allow latest openssl version run with gcp cups?

**Comment by jacobmarble** [comment]
I don't know of any part of the connector that requires a particular OpenSSL version. The code doesn't use OpenSSL directly, but it does depend on CUPS, SNMP and Avahi C libraries. If you change the underlying OpenSSL library, perhaps the connector needs to be rebuilt?

**Comment by arnauhe** [comment]
Actually, I took gcp-cups-connector-linux-amd64-2015.10.05.tar.gz package. I don't build anything. I extracted the package and run the connector but it required OPENSSL_1.0.0. So I suppose that it comes from the connector itself.

**Comment by arnauhe** [comment]
Here my error when launching gcp cups connector
[root@saai-cupsp01 cups-connector]# ./gcp-cups-connector: /usr/lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./gcp-cups-connector)

**Comment by jay0lee** [comment]
Hi Arnaud, I was able to compile the connector on RHEL 6.7. Here are my binaries. Can you give them a try?

https://drive.google.com/file/d/0B0YvUuHHn3MnazdicDU3UG9qcnM/view?usp=sharing

**Comment by arnauhe** [comment]
Hey Jay,
Thanks a lot, It works as expected!

Meanwhile, I did some command and I remove libssl librairies.. to downgrade
openssl version.
For time being, It works but I'm afraid I can't connect anymore afterwards


Cordialement,
Best Regards,

Arnaud HENRI
Air Liquide / Global End-User Services
Tel:    +33 (0)1 70 92 38 15
mailto:Arnaud.HENRI-SC@airliquide.com

*Check My calendar
<http://www.google.com/calendar/embed?src=arnaud.henri-sc%40airliquide.com&ctz=Europe/Paris>*

**Comment by jay0lee** [comment]
Hi Arnaud, sounds like something may be borked on that server that's breaking the compile. It's the "scorched earth" approach but a clean reinstall may be in order at some point :-/

I think we can close out this issue for now as it doesn't seem to be an issue with gcp-cups-connector but email me if you have further issues/questions.

Jay

**Comment by jacobmarble** [comment]
@arnauhe I assumed that you had built the binaries yourself because the binaries are known not to work on Red Hat or Fedora, due to this very issue. I'll have to make that clearer in the future.
